# Generated by Django 6.1.1 on 2026-09-11 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(choices=[('notebook_i7', 'Notebook(Avançado - i7)'), ('notebook_i5', 'Notebook(Básico - i5)'), ('workstation', 'Desktop(Avançado - i7)'), ('optiplex', 'Desktop(Básico - i5)'), ('monitor', 'Monitor'), ('mac_mini', 'Mac mini'), ('access_point', 'AP'), ('tela_interativa', 'Tela interativa'), ('equipamento_sampacast', 'Equipamento áudio/vídeo')], max_length=30)),
                ('codigo', models.CharField(max_length=35)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('uso', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('observacao', models.CharField(blank=True, max_length=250)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processado', 'Processado'), ('descartado', 'Descartado')], default='pendente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
